export const PROFESSION_SUGGESTIONS = [
  "Développeur",
  "Designer",
  "Graphiste",
  "Chef de projet",
  "Product manager",
  "Marketing",
  "Commercial",
  "Community manager",
  "Comptable",
  "Avocat",
  "Consultant",
  "Photographe",
  "Architecte",
  "Rédacteur",
  "Data analyst",
  "RH",
  "Entrepreneur",
  "Étudiant",
  "Coach",
  "Traducteur",
  "Ingénieur",
  "UX / UI",
  "Finance",
  "Juriste",
  "Freelance",
  "Formateur",
  "Vidéaste",
  "Motion designer",
  "DevOps",
  "Data scientist",
  "Growth",
  "SEO",
  "Journaliste",
  "Architecte d’intérieur",
];

export const SKILL_SUGGESTIONS = [
  "React",
  "Node.js",
  "Python",
  "Figma",
  "UI/UX",
  "SEO",
  "Ads",
  "Copywriting",
  "Vidéo",
  "Photo",
  "Excel",
  "Compta",
  "Juridique",
  "Formation",
  "No-code",
  "IA",
  "Sales",
  "Branding",
  "WordPress",
  "Mobile",
  "TypeScript",
  "Next.js",
  "Illustration",
  "Montage",
  "3D",
  "Social media",
  "Négociation",
  "Stratégie",
  "Product",
  "Design system",
];
